### ISSUE TITLE
 Button Functionality Missing And Its Styling And Position

### ISSUE THREAD

**Issue by cxde-Sujal** [SlaydeSequeira/SIH-WEB#9]
You have buttons labeled "front," "back," "left," and "right," but there's no code for switching images when these buttons are clicked.The buttons currently don’t have any specific positioning or styling. They may overlap or not be easily accessible on different screen sizes.
**@SlaydeSequeira assign it to me for Hacktober**

**Comment by SlaydeSequeira** [comment]
i assigned the issue to u, sorry though i think the deadline of hacktober is missed. Hopefully the consider this assignment aswell.
